###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Alvey, CS165
# Author:
#     Ali Cope
# Summary:
#     This program will create a library for inventory. This will allow the
#     user to add products. Calculate their cost on a receipt, manage
#     inventory, calculate shipping and sales tax. 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

