###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Alvey, CS165
# Author:
#     Ali Cope
# Summary:
#     E-commerce program to track inventory, customer name, address and a
#     customer order. Address, Customer, Product and Order are all new
#     clases that can be used as objects to track information and perform
#     functions for the user like getting and setting information for each
#     class and displaying it in various forms  
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

